services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build: ./node
    container_name: app
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/nodedb

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  default:
    driver: bridge
